name       : naev
version    : 0.9.1
release    : 15
source     :
    - https://github.com/naev/naev/releases/download/v0.9.1/naev-0.9.1-source.tar.xz : 08943474f68637edd0c28a87a7ed312a306d69786bd571d8480ae5d6015df1ec
license    : GPL-3.0-or-later
component  : games.action
summary    : Naev is a 2D space trading and combat game, in a similar vein to Escape Velocity
description: |
    NAEV is played from a top-down perspective, featuring fast-paced combat, many ships, a large variety of equipment and a large galaxy to explore. The game is highly open-ended, letting you proceed at your own pace.
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(freetype2)
    - pkgconfig(libunibreak)
    - pkgconfig(libwebp)
    - pkgconfig(luajit)
    - pkgconfig(openal)
    - pkgconfig(openblas)
    - pkgconfig(physfs)
    - pkgconfig(vorbisfile)
    - glpk-devel
    - mutagen
    - suitesparse-devel
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rfv $installdir/usr/share/doc
