name       : naev
version    : 0.7.0
release    : 2
source     :
    - https://github.com/naev/naev/archive/naev-0.7.0.tar.gz : b995813ffb67d68a71d55184ac00513e86f048335635d0692d866e2f2107e170
license    : GPL-3.0
component  : games.action
summary    : Naev is a 2D space trading and combat game, in a similar vein to Escape Velocity
description: |
    NAEV is played from a top-down perspective, featuring fast-paced combat, many
    ships, a large variety of equipment and a large galaxy to explore. The game is
    highly open-ended, letting you proceed at your own pace.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(openal)
    - pkgconfig(libpng)
    - pkgconfig(libzip)
    - pkgconfig(luajit)
    - pkgconfig(sdl2)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(vorbisfile)
    - pkgconfig(vorbis)
setup      : |
    %reconfigure --disable-debug --disable-shave
build      : |
    %make
install    : |
    %make_install
