name       : naev
version    : 0.8.0
release    : 12
source     :
    - https://github.com/naev/naev/releases/download/v0.8.0/naev-0.8.0-source.tar.gz : 06a66179eea1e5160b70ee32965fb9321709aea4138719ca1e29712f842db4ee
license    : GPL-3.0-or-later
component  : games.action
summary    : Naev is a 2D space trading and combat game, in a similar vein to Escape Velocity
description: |
    NAEV is played from a top-down perspective, featuring fast-paced combat, many ships, a large variety of equipment and a large galaxy to explore. The game is highly open-ended, letting you proceed at your own pace.
builddeps  :
    - pkgconfig(SDL2_mixer)
    - pkgconfig(freetype2)
    - pkgconfig(glu)
    - pkgconfig(luajit)
    - pkgconfig(openal)
    - pkgconfig(vorbisfile)
setup      : |
    %configure --disable-debug --disable-shave
build      : |
    %make
install    : |
    %make_install
