name       : naev
version    : 0.6.1
release    : 1
source     :
    - https://github.com/naev/naev/archive/naev-0.6.1.tar.gz : c9d55c55142cd395d3b23583ef6c613f0548941b90b190efca34b29cebf9e527
license    : GPL-3.0
component  : games.action
summary    : Naev is a 2D space trading and combat game
description: |
    Naev is a 2D space trading and combat game, taking inspiration from the Escape Velocity series, among others.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(openal)
    - pkgconfig(libpng)
    - pkgconfig(libzip)
    - pkgconfig(luajit)
    - pkgconfig(sdl2)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(vorbisfile)
    - pkgconfig(vorbis)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
